---
title: "GroupProject"
author: "LAUREN"
date: "11/23/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
nh = data.frame(NHANES::NHANES)
library("Hmisc")
library("dplyr")
library("tidyr")
library("sas7bdat")
library("corrplot")
library("gtsummary")
library("dplyr")
```


```{r}
varinterst = c("Age","Gender","Race1","PhysActive","Depressed","Diabetes","BPSysAve", "BPDiaAve", "TotChol", "Testosterone", "RegularMarij", "BMI")

nh1 = nh[,varinterst]
nh1 <- nh1[ which(nh1$Age >=18 & nh1$Age <=59), ]

nh1 <- nh1 %>%
  mutate(HypT = if_else(nh1$BPSysAve >= 130 | nh1$BPDiaAve >=80, 1, 0)) #Add hypertension variable
nh1 <- nh1 %>%
  mutate(Sex = ifelse(nh1$Gender == "female", 1, 0)) 
nh1 <- nh1 %>%
  mutate(PhysAc = ifelse(nh1$PhysActive == "No", 0, 1)) 
nh1 <- nh1 %>%
  mutate(Diabete = ifelse(nh1$Diabetes == "No", 0, 1))
nh1 <- nh1 %>%
  mutate(Depress = ifelse(nh1$Depressed == "None", 0, 1))
nh1 <- nh1 %>%
  mutate(RegularMarij2 = ifelse(nh1$RegularMarij == "No", 0, 1))
nh1$TotChol = log(nh1$TotChol)
nh1$Incomplete = complete.cases(nh1)
nh1$Race1 = as.factor(nh1$Race1)

drops = c("Sex")
nhF= nh1[ which(nh1$Sex == 1), ]
nhM = nh1[ which(nh1$Sex == 0), ]
nhF = nhF[,!(names(nhF) %in% drops)]
nhM = nhM[,!(names(nhM) %in% drops)]
```


```{r}
## Shiny app
nhF %>%
 tbl_summary(by = Incomplete,
              missing = "no",
              statistic = list(all_continuous() ~ "{mean} ({sd})",
                               all_categorical() ~ "{n} ({p}%)"),
              ) %>%
  add_n %>%
  add_p(test = list(Age ~ "t.test",
                    Race1 ~ "chisq.test",
                    PhysAc ~ "chisq.test",
                    Depress ~ "chisq.test",
                    Diabete ~ "chisq.test",
                    HypT ~ "chisq.test",
                    TotChol ~ "t.test",
                    Testosterone ~ "t.test",
                    RegularMarij2 ~ "chisq.test"),
        test.args = all_tests("t.test") ~ list(var.equal = TRUE), ## Important argument! 
        pvalue_fun = function(x) style_pvalue(x, digits = 2)) %>%
  bold_p(t = 0.05) %>%
  bold_labels
```


```{r}
nhM %>%
 tbl_summary(by = Incomplete,
              missing = "no",
              statistic = list(all_continuous() ~ "{mean} ({sd})",
                               all_categorical() ~ "{n} ({p}%)"),
              ) %>%
  add_n %>%
  add_p(test = list(Age ~ "t.test",
                    Race1 ~ "chisq.test",
                    PhysAc ~ "chisq.test",
                    Depress ~ "chisq.test",
                    Diabete ~ "chisq.test",
                    HypT ~ "chisq.test",
                    TotChol ~ "t.test",
                    Testosterone ~ "t.test",
                    RegularMarij2 ~ "chisq.test"),
        test.args = all_tests("t.test") ~ list(var.equal = TRUE),## Important argument! 
        pvalue_fun = function(x) style_pvalue(x, digits = 2)) %>%
  bold_p(t = 0.05) %>%
  bold_labels
```


```{r}
## Complete case model nh2
nh2 <- nh1 %>% drop_na() #drop anything with NA
## Full model with age as continuous variable
m1 =  lm(log(Testosterone)~
             Age + Sex + Race1 + PhysAc + Depress + 
             Diabete + HypT+ TotChol + RegularMarij2, 
         data = nh2)
summary(m1)
```


```{r}
## quantile(nh2$Age, probs = seq(0, 1, 0.25))
## Change Age into categorical variable
AgeQ1 <- nh2$Age<28
AgeQ2 <- nh2$Age>=28 & nh2$Age<39
AgeQ3 <- nh2$Age>=39 & nh2$Age<49
AgeQ4 <- nh2$Age>=49 & nh2$Age<59

m_ageC <- lm(log(Testosterone)~
                 AgeQ2 + AgeQ3 + AgeQ4 + 
                 Sex + Race1 + PhysAc + Depress + 
                 Diabete + HypT+ TotChol + RegularMarij2, 
             data = nh2)
summary(m_ageC)
```

```{r}
## Check age linearity
plot(1:3, m_ageC$coefficients[2:4])
```

```{r}
## full model with interaction
m_ageC_it <- lm(log(Testosterone) ~ 
                    AgeQ2 + AgeQ3 + AgeQ4 + 
                    Sex + Race1 + PhysAc + Depress + Diabete + 
                    HypT+ TotChol + RegularMarij2 +
                    RegularMarij2*(AgeQ2 + AgeQ3 + AgeQ4 + Sex + 
                                   Race1 + PhysAc + Depress + 
                                       Diabete + HypT+ TotChol), 
                data = nh2)
summary(m_ageC_it)
```

```{r}
## Check co-linearity
cor(nh2[c("Diabete", "TotChol", "HypT", "PhysAc","Depress")])
```
## linearity check
```{r}
car::avPlots(m_ageC_it)
```
```{r}
## For independence, we check literature. 
```

```{r}
## model without iteraction
m_ageC_wo_it <- lm(log(Testosterone)~AgeQ2 + AgeQ3 + AgeQ4 + Sex + Race1 + PhysAc + Depress + Diabete + HypT+ TotChol + RegularMarij2, nh2)
plot(m_ageC_wo_it$fitted.values, m_ageC_wo_it$residuals)
plot(m_ageC$fitted.values, m_ageC$residuals)
summary(log(nh2$Testosterone))
hist(log(nh2$Testosterone))
```



```{r}
StraSex <- function(nh) {
    nh2F <- nh %>% drop_na() #drop anything with NA
    q <- quantile(nh2F$Age, probs = seq(0, 1, 0.25))
    AgeQ1F <- nh2F$Age<q[2]
    AgeQ2F <- nh2F$Age>=q[2] & nh2F$Age<q[3]
    AgeQ3F <- nh2F$Age>=q[3] & nh2F$Age<q[4]
    AgeQ4F <- nh2F$Age>=q[4] & nh2F$Age<q[5]
    mf =  lm(log(Testosterone)~AgeQ2F+AgeQ3F+AgeQ4F + Race1 + PhysAc + Depress + Diabete + HypT+ TotChol + RegularMarij2, nh2F)
    return(mf)
}
## female
mf <- StraSex(nhF)
summary(mf)
## male
mm <- StraSex(nhM)
summary(mm)
```
```{r}
## linearity for female
car::avPlots(mf)

```
```{r}
## linearity for male
car::avPlots(mm)
```

```{r}
## equal variance
plot(mf$fitted.values, mf$residuals)
plot(mm$fitted.values, mm$residuals)
```

```{r}
## normality
hist(m_ageC$residuals)
hist(mf$residuals)
hist(mm$residuals)
```
```{r}
## normality
car::qqPlot(m_ageC$residuals)
car::qqPlot(mf$residuals)
car::qqPlot(mm$residuals)
```
```{r}
## all 4 assumptions check
```

```{r}
## duplicate the operations
nh2M$RN <- as.numeric(nh2M$Race1)
cor(nh2M[c("Age","PhysAc" ,"RN", "Depress" , "Diabete" , "HypT" , "TotChol" , "RegularMarij2")])
```


```{r}
mf_w_it =  lm(log(Testosterone)~AgeQ2F+AgeQ3F+AgeQ4F + Race1 + PhysAc + Depress + Diabete + HypT+ TotChol + RegularMarij2 + RegularMarij2*(AgeQ2F+AgeQ3F+AgeQ4F + Race1 + PhysAc + Depress + Diabete + HypT+ TotChol), nh2F)
summary(mf_w_it)
```

```{r}
mm_w_it =  lm(log(Testosterone)~AgeQ2+AgeQ3+AgeQ4 + Race1 + PhysAc + Depress + Diabete + HypT+ TotChol + RegularMarij2 + RegularMarij2*(AgeQ2+AgeQ3+AgeQ4 + Race1 + PhysAc + Depress + Diabete + HypT+ TotChol), nh2M)
summary(mm_w_it)
```

















